# Generated by Django 5.2.5 on 2025-10-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gessdemn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=None, max_length=10, null=True)),
                ('ai_suggestion', models.TextField(blank=True, null=True)),
                ('ai_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
    ]
